# GENERATED by scripts/generate_types.py from docs/openapi.json — DO NOT EDIT.
# OpenAPI version: 0.1.0. Re-run the script after the contract changes; CI fails on drift.
"""Request and response shapes of the SDK-facing API, as TypedDicts (plain dicts at runtime)."""

from __future__ import annotations

from typing import Any, Literal, TypedDict

EntitlementReason = Literal["no_subscription", "not_in_plan", "hard_limit_reached", "soft_limit_exceeded", "insufficient_credits"]

FeatureType = Literal["boolean", "metered"]

SubscriptionStatus = Literal["active", "trialing", "past_due", "paused", "canceled", "expired"]


class CreditBalanceResponse(TypedDict):
    id: str
    project_id: str
    customer_external_id: str
    balance: str
    total_granted: str
    total_consumed: str
    version: int
    created_at: str
    updated_at: str


class _CreditDeductRequestRequired(TypedDict):
    customer_external_id: str
    amount: float | str


class CreditDeductRequest(_CreditDeductRequestRequired, total=False):
    description: str | None
    idempotency_key: str | None
    metadata: dict[str, Any]


class _CreditGrantRequestRequired(TypedDict):
    customer_external_id: str
    amount: float | str


class CreditGrantRequest(_CreditGrantRequestRequired, total=False):
    description: str | None
    idempotency_key: str | None
    metadata: dict[str, Any]


class CreditTransactionResponse(TypedDict):
    id: str
    project_id: str
    customer_external_id: str
    transaction_type: str
    amount: str
    balance_before: str
    balance_after: str
    description: str | None
    idempotency_key: str | None
    metadata_: dict[str, Any]
    created_at: str


class _EntitlementResponseRequired(TypedDict):
    feature: str
    feature_type: FeatureType
    allowed: bool


class EntitlementResponse(_EntitlementResponseRequired, total=False):
    reason: EntitlementReason | None
    limit_type: str | None
    included: int | None
    used: str | None
    remaining: str | None
    period_start: str | None
    period_end: str | None


class EntitlementsResponse(TypedDict):
    customer_id: str
    environment: str
    subscription_id: str | None
    plan_id: str | None
    period_end: str | None
    entitlements: list[EntitlementResponse]


class PlanMeterLimitResponse(TypedDict):
    id: str
    plan_id: str
    meter_id: str
    included_units: int | None
    overage_rate: str | None
    limit_type: str


class PlanResponse(TypedDict):
    id: str
    project_id: str
    name: str
    slug: str
    description: str | None
    billing_period: str
    price: str
    currency: str
    trial_days: int
    is_active: bool
    is_public: bool
    metadata_: dict[str, Any]
    meter_limits: list[PlanMeterLimitResponse]
    features: list[str]
    created_at: str
    updated_at: str


class _SubscriptionCreateRequestRequired(TypedDict):
    plan_id: str
    customer_external_id: str


class SubscriptionCreateRequest(_SubscriptionCreateRequestRequired, total=False):
    metadata: dict[str, Any]
    idempotency_key: str | None


class SubscriptionResponse(TypedDict):
    id: str
    project_id: str
    plan_id: str
    customer_external_id: str
    status: str
    current_period_start: str
    current_period_end: str | None
    trial_end_date: str | None
    canceled_at: str | None
    metadata_: dict[str, Any]
    created_at: str
    updated_at: str


class SubscriptionUpdateRequest(TypedDict, total=False):
    status: SubscriptionStatus | None
    metadata: dict[str, Any] | None


class UsageEventBatchRequest(TypedDict):
    events: list[UsageEventRequest]


class _UsageEventRequestRequired(TypedDict):
    event_name: str
    customer_external_id: str


class UsageEventRequest(_UsageEventRequestRequired, total=False):
    value: float | str
    properties: dict[str, Any]
    idempotency_key: str | None
    timestamp: str | None


class UsageEventResponse(TypedDict):
    id: str
    project_id: str
    meter_id: str
    customer_external_id: str
    event_name: str
    value: str
    properties: dict[str, Any]
    idempotency_key: str | None
    processed: bool
    timestamp: str
    created_at: str


class UsageSummaryItem(TypedDict):
    meter_id: str
    meter_name: str
    event_name: str
    aggregation_type: str
    value: str
    event_count: int


class UsageSummaryResponse(TypedDict):
    project_id: str
    customer_external_id: str
    from_: str | None
    to: str | None
    meters: list[UsageSummaryItem]


__all__ = [
    "CreditBalanceResponse",
    "CreditDeductRequest",
    "CreditGrantRequest",
    "CreditTransactionResponse",
    "EntitlementReason",
    "EntitlementResponse",
    "EntitlementsResponse",
    "FeatureType",
    "PlanMeterLimitResponse",
    "PlanResponse",
    "SubscriptionCreateRequest",
    "SubscriptionResponse",
    "SubscriptionStatus",
    "SubscriptionUpdateRequest",
    "UsageEventBatchRequest",
    "UsageEventRequest",
    "UsageEventResponse",
    "UsageSummaryItem",
    "UsageSummaryResponse",
]
